#ifndef MINIC_TABELA_LL1_H
#define MINIC_TABELA_LL1_H

typedef struct {
    const char *variavel;
    const char *terminal;
    int regra;
} EntradaLL1;

static const EntradaLL1 TABELA_LL1[] = {

    {"programa", "BOOL", 1},
    {"programa", "BREAK", 1},
    {"programa", "CHAR", 1},
    {"programa", "CHAR_LIT", 1},
    {"programa", "CONTINUE", 1},
    {"programa", "EOF", 1},
    {"programa", "FALSE", 1},
    {"programa", "FLOAT", 1},
    {"programa", "FLOAT_LIT", 1},
    {"programa", "FOR", 1},
    {"programa", "IDENT", 1},
    {"programa", "IF", 1},
    {"programa", "INT", 1},
    {"programa", "INT_LIT", 1},
    {"programa", "LBRACE", 1},
    {"programa", "LPAREN", 1},
    {"programa", "MINUS", 1},
    {"programa", "NOT", 1},
    {"programa", "PRINT", 1},
    {"programa", "READ", 1},
    {"programa", "RETURN", 1},
    {"programa", "SEMICOLON", 1},
    {"programa", "STRING_LIT", 1},
    {"programa", "TRUE", 1},
    {"programa", "VOID", 1},
    {"programa", "WHILE", 1},

    {"lista_elementos", "BOOL", 2},
    {"lista_elementos", "BREAK", 2},
    {"lista_elementos", "CHAR", 2},
    {"lista_elementos", "CHAR_LIT", 2},
    {"lista_elementos", "CONTINUE", 2},
    {"lista_elementos", "EOF", 3},
    {"lista_elementos", "FALSE", 2},
    {"lista_elementos", "FLOAT", 2},
    {"lista_elementos", "FLOAT_LIT", 2},
    {"lista_elementos", "FOR", 2},
    {"lista_elementos", "IDENT", 2},
    {"lista_elementos", "IF", 2},
    {"lista_elementos", "INT", 2},
    {"lista_elementos", "INT_LIT", 2},
    {"lista_elementos", "LBRACE", 2},
    {"lista_elementos", "LPAREN", 2},
    {"lista_elementos", "MINUS", 2},
    {"lista_elementos", "NOT", 2},
    {"lista_elementos", "PRINT", 2},
    {"lista_elementos", "READ", 2},
    {"lista_elementos", "RETURN", 2},
    {"lista_elementos", "SEMICOLON", 2},
    {"lista_elementos", "STRING_LIT", 2},
    {"lista_elementos", "TRUE", 2},
    {"lista_elementos", "VOID", 2},
    {"lista_elementos", "WHILE", 2},

    {"elemento", "BOOL", 4},
    {"elemento", "BREAK", 5},
    {"elemento", "CHAR", 4},
    {"elemento", "CHAR_LIT", 5},
    {"elemento", "CONTINUE", 5},
    {"elemento", "FALSE", 5},
    {"elemento", "FLOAT", 4},
    {"elemento", "FLOAT_LIT", 5},
    {"elemento", "FOR", 5},
    {"elemento", "IDENT", 5},
    {"elemento", "IF", 5},
    {"elemento", "INT", 4},
    {"elemento", "INT_LIT", 5},
    {"elemento", "LBRACE", 5},
    {"elemento", "LPAREN", 5},
    {"elemento", "MINUS", 5},
    {"elemento", "NOT", 5},
    {"elemento", "PRINT", 5},
    {"elemento", "READ", 5},
    {"elemento", "RETURN", 5},
    {"elemento", "SEMICOLON", 5},
    {"elemento", "STRING_LIT", 5},
    {"elemento", "TRUE", 5},
    {"elemento", "VOID", 4},
    {"elemento", "WHILE", 5},

    {"decl_ou_funcao", "BOOL", 6},
    {"decl_ou_funcao", "CHAR", 6},
    {"decl_ou_funcao", "FLOAT", 6},
    {"decl_ou_funcao", "INT", 6},
    {"decl_ou_funcao", "VOID", 6},

    {"resto_decl_func", "ASSIGN", 8},
    {"resto_decl_func", "COMMA", 8},
    {"resto_decl_func", "LBRACKET", 8},
    {"resto_decl_func", "LPAREN", 7},
    {"resto_decl_func", "SEMICOLON", 8},

    {"resto_df", "BOOL", 9},
    {"resto_df", "CHAR", 9},
    {"resto_df", "FLOAT", 9},
    {"resto_df", "INT", 9},
    {"resto_df", "RPAREN", 10},

    {"tipo_retorno", "BOOL", 11},
    {"tipo_retorno", "CHAR", 11},
    {"tipo_retorno", "FLOAT", 11},
    {"tipo_retorno", "INT", 11},
    {"tipo_retorno", "VOID", 12},

    {"tipo", "BOOL", 15},
    {"tipo", "CHAR", 16},
    {"tipo", "FLOAT", 14},
    {"tipo", "INT", 13},

    {"parametros", "BOOL", 17},
    {"parametros", "CHAR", 17},
    {"parametros", "FLOAT", 17},
    {"parametros", "INT", 17},

    {"resto_parametros", "COMMA", 18},
    {"resto_parametros", "RPAREN", 19},

    {"parametro", "BOOL", 20},
    {"parametro", "CHAR", 20},
    {"parametro", "FLOAT", 20},
    {"parametro", "INT", 20},

    {"resto_parametro", "COMMA", 22},
    {"resto_parametro", "LBRACKET", 21},
    {"resto_parametro", "RPAREN", 22},

    {"bloco", "LBRACE", 23},

    {"itens_bloco", "BOOL", 24},
    {"itens_bloco", "BREAK", 24},
    {"itens_bloco", "CHAR", 24},
    {"itens_bloco", "CHAR_LIT", 24},
    {"itens_bloco", "CONTINUE", 24},
    {"itens_bloco", "FALSE", 24},
    {"itens_bloco", "FLOAT", 24},
    {"itens_bloco", "FLOAT_LIT", 24},
    {"itens_bloco", "FOR", 24},
    {"itens_bloco", "IDENT", 24},
    {"itens_bloco", "IF", 24},
    {"itens_bloco", "INT", 24},
    {"itens_bloco", "INT_LIT", 24},
    {"itens_bloco", "LBRACE", 24},
    {"itens_bloco", "LPAREN", 24},
    {"itens_bloco", "MINUS", 24},
    {"itens_bloco", "NOT", 24},
    {"itens_bloco", "PRINT", 24},
    {"itens_bloco", "RBRACE", 25},
    {"itens_bloco", "READ", 24},
    {"itens_bloco", "RETURN", 24},
    {"itens_bloco", "SEMICOLON", 24},
    {"itens_bloco", "STRING_LIT", 24},
    {"itens_bloco", "TRUE", 24},
    {"itens_bloco", "WHILE", 24},

    {"item_bloco", "BOOL", 26},
    {"item_bloco", "BREAK", 27},
    {"item_bloco", "CHAR", 26},
    {"item_bloco", "CHAR_LIT", 27},
    {"item_bloco", "CONTINUE", 27},
    {"item_bloco", "FALSE", 27},
    {"item_bloco", "FLOAT", 26},
    {"item_bloco", "FLOAT_LIT", 27},
    {"item_bloco", "FOR", 27},
    {"item_bloco", "IDENT", 27},
    {"item_bloco", "IF", 27},
    {"item_bloco", "INT", 26},
    {"item_bloco", "INT_LIT", 27},
    {"item_bloco", "LBRACE", 27},
    {"item_bloco", "LPAREN", 27},
    {"item_bloco", "MINUS", 27},
    {"item_bloco", "NOT", 27},
    {"item_bloco", "PRINT", 27},
    {"item_bloco", "READ", 27},
    {"item_bloco", "RETURN", 27},
    {"item_bloco", "SEMICOLON", 27},
    {"item_bloco", "STRING_LIT", 27},
    {"item_bloco", "TRUE", 27},
    {"item_bloco", "WHILE", 27},

    {"declaracao_local", "BOOL", 28},
    {"declaracao_local", "CHAR", 28},
    {"declaracao_local", "FLOAT", 28},
    {"declaracao_local", "INT", 28},

    {"resto_dl", "COMMA", 29},
    {"resto_dl", "SEMICOLON", 30},

    {"declarador", "IDENT", 31},

    {"resto_d", "ASSIGN", 32},
    {"resto_d", "COMMA", 34},
    {"resto_d", "LBRACKET", 33},
    {"resto_d", "SEMICOLON", 34},

    {"tamanho", "INT_LIT", 35},

    {"inicializacao", "ASSIGN", 36},

    {"comando", "BREAK", 42},
    {"comando", "CHAR_LIT", 46},
    {"comando", "CONTINUE", 43},
    {"comando", "FALSE", 46},
    {"comando", "FLOAT_LIT", 46},
    {"comando", "FOR", 40},
    {"comando", "IDENT", 46},
    {"comando", "IF", 38},
    {"comando", "INT_LIT", 46},
    {"comando", "LBRACE", 37},
    {"comando", "LPAREN", 46},
    {"comando", "MINUS", 46},
    {"comando", "NOT", 46},
    {"comando", "PRINT", 44},
    {"comando", "READ", 45},
    {"comando", "RETURN", 41},
    {"comando", "SEMICOLON", 46},
    {"comando", "STRING_LIT", 46},
    {"comando", "TRUE", 46},
    {"comando", "WHILE", 39},

    {"comando_bloco", "LBRACE", 47},

    {"comando_if", "IF", 48},

    {"resto_cm_if", "BOOL", 50},
    {"resto_cm_if", "BREAK", 50},
    {"resto_cm_if", "CHAR", 50},
    {"resto_cm_if", "CHAR_LIT", 50},
    {"resto_cm_if", "CONTINUE", 50},
    {"resto_cm_if", "ELSE", 49},
    {"resto_cm_if", "EOF", 50},
    {"resto_cm_if", "FALSE", 50},
    {"resto_cm_if", "FLOAT", 50},
    {"resto_cm_if", "FLOAT_LIT", 50},
    {"resto_cm_if", "FOR", 50},
    {"resto_cm_if", "IDENT", 50},
    {"resto_cm_if", "IF", 50},
    {"resto_cm_if", "INT", 50},
    {"resto_cm_if", "INT_LIT", 50},
    {"resto_cm_if", "LBRACE", 50},
    {"resto_cm_if", "LPAREN", 50},
    {"resto_cm_if", "MINUS", 50},
    {"resto_cm_if", "NOT", 50},
    {"resto_cm_if", "PRINT", 50},
    {"resto_cm_if", "RBRACE", 50},
    {"resto_cm_if", "READ", 50},
    {"resto_cm_if", "RETURN", 50},
    {"resto_cm_if", "SEMICOLON", 50},
    {"resto_cm_if", "STRING_LIT", 50},
    {"resto_cm_if", "TRUE", 50},
    {"resto_cm_if", "VOID", 50},
    {"resto_cm_if", "WHILE", 50},

    {"comando_while", "WHILE", 51},

    {"comando_for", "FOR", 52},

    {"comando_return", "RETURN", 53},

    {"comando_break", "BREAK", 54},

    {"comando_continue", "CONTINUE", 55},

    {"comando_print", "PRINT", 56},

    {"argumento_print", "CHAR_LIT", 57},
    {"argumento_print", "FALSE", 57},
    {"argumento_print", "FLOAT_LIT", 57},
    {"argumento_print", "IDENT", 57},
    {"argumento_print", "INT_LIT", 57},
    {"argumento_print", "LPAREN", 57},
    {"argumento_print", "MINUS", 57},
    {"argumento_print", "NOT", 57},
    {"argumento_print", "STRING_LIT", 57},
    {"argumento_print", "TRUE", 57},

    {"comando_read", "READ", 58},

    {"comando_expressao", "CHAR_LIT", 59},
    {"comando_expressao", "FALSE", 59},
    {"comando_expressao", "FLOAT_LIT", 59},
    {"comando_expressao", "IDENT", 59},
    {"comando_expressao", "INT_LIT", 59},
    {"comando_expressao", "LPAREN", 59},
    {"comando_expressao", "MINUS", 59},
    {"comando_expressao", "NOT", 59},
    {"comando_expressao", "SEMICOLON", 59},
    {"comando_expressao", "STRING_LIT", 59},
    {"comando_expressao", "TRUE", 59},

    {"exp_opcional", "CHAR_LIT", 60},
    {"exp_opcional", "FALSE", 60},
    {"exp_opcional", "FLOAT_LIT", 60},
    {"exp_opcional", "IDENT", 60},
    {"exp_opcional", "INT_LIT", 60},
    {"exp_opcional", "LPAREN", 60},
    {"exp_opcional", "MINUS", 60},
    {"exp_opcional", "NOT", 60},
    {"exp_opcional", "RPAREN", 61},
    {"exp_opcional", "SEMICOLON", 61},
    {"exp_opcional", "STRING_LIT", 60},
    {"exp_opcional", "TRUE", 60},

    {"expressao", "CHAR_LIT", 62},
    {"expressao", "FALSE", 62},
    {"expressao", "FLOAT_LIT", 62},
    {"expressao", "IDENT", 62},
    {"expressao", "INT_LIT", 62},
    {"expressao", "LPAREN", 62},
    {"expressao", "MINUS", 62},
    {"expressao", "NOT", 62},
    {"expressao", "STRING_LIT", 62},
    {"expressao", "TRUE", 62},

    {"resto_atribuicao", "ASSIGN", 63},
    {"resto_atribuicao", "COMMA", 64},
    {"resto_atribuicao", "RBRACKET", 64},
    {"resto_atribuicao", "RPAREN", 64},
    {"resto_atribuicao", "SEMICOLON", 64},

    {"expressao_or", "CHAR_LIT", 65},
    {"expressao_or", "FALSE", 65},
    {"expressao_or", "FLOAT_LIT", 65},
    {"expressao_or", "IDENT", 65},
    {"expressao_or", "INT_LIT", 65},
    {"expressao_or", "LPAREN", 65},
    {"expressao_or", "MINUS", 65},
    {"expressao_or", "NOT", 65},
    {"expressao_or", "STRING_LIT", 65},
    {"expressao_or", "TRUE", 65},

    {"aux_exp_or", "ASSIGN", 67},
    {"aux_exp_or", "COMMA", 67},
    {"aux_exp_or", "OR", 66},
    {"aux_exp_or", "RBRACKET", 67},
    {"aux_exp_or", "RPAREN", 67},
    {"aux_exp_or", "SEMICOLON", 67},

    {"expressao_and", "CHAR_LIT", 68},
    {"expressao_and", "FALSE", 68},
    {"expressao_and", "FLOAT_LIT", 68},
    {"expressao_and", "IDENT", 68},
    {"expressao_and", "INT_LIT", 68},
    {"expressao_and", "LPAREN", 68},
    {"expressao_and", "MINUS", 68},
    {"expressao_and", "NOT", 68},
    {"expressao_and", "STRING_LIT", 68},
    {"expressao_and", "TRUE", 68},

    {"aux_exp_and", "AND", 69},
    {"aux_exp_and", "ASSIGN", 70},
    {"aux_exp_and", "COMMA", 70},
    {"aux_exp_and", "OR", 70},
    {"aux_exp_and", "RBRACKET", 70},
    {"aux_exp_and", "RPAREN", 70},
    {"aux_exp_and", "SEMICOLON", 70},

    {"expressao_igualdade", "CHAR_LIT", 71},
    {"expressao_igualdade", "FALSE", 71},
    {"expressao_igualdade", "FLOAT_LIT", 71},
    {"expressao_igualdade", "IDENT", 71},
    {"expressao_igualdade", "INT_LIT", 71},
    {"expressao_igualdade", "LPAREN", 71},
    {"expressao_igualdade", "MINUS", 71},
    {"expressao_igualdade", "NOT", 71},
    {"expressao_igualdade", "STRING_LIT", 71},
    {"expressao_igualdade", "TRUE", 71},

    {"aux_exp_igualdade", "AND", 74},
    {"aux_exp_igualdade", "ASSIGN", 74},
    {"aux_exp_igualdade", "COMMA", 74},
    {"aux_exp_igualdade", "EQ", 72},
    {"aux_exp_igualdade", "NE", 73},
    {"aux_exp_igualdade", "OR", 74},
    {"aux_exp_igualdade", "RBRACKET", 74},
    {"aux_exp_igualdade", "RPAREN", 74},
    {"aux_exp_igualdade", "SEMICOLON", 74},

    {"expressao_relacional", "CHAR_LIT", 75},
    {"expressao_relacional", "FALSE", 75},
    {"expressao_relacional", "FLOAT_LIT", 75},
    {"expressao_relacional", "IDENT", 75},
    {"expressao_relacional", "INT_LIT", 75},
    {"expressao_relacional", "LPAREN", 75},
    {"expressao_relacional", "MINUS", 75},
    {"expressao_relacional", "NOT", 75},
    {"expressao_relacional", "STRING_LIT", 75},
    {"expressao_relacional", "TRUE", 75},

    {"aux_exp_relacional", "AND", 77},
    {"aux_exp_relacional", "ASSIGN", 77},
    {"aux_exp_relacional", "COMMA", 77},
    {"aux_exp_relacional", "EQ", 77},
    {"aux_exp_relacional", "GE", 76},
    {"aux_exp_relacional", "GT", 76},
    {"aux_exp_relacional", "LE", 76},
    {"aux_exp_relacional", "LT", 76},
    {"aux_exp_relacional", "NE", 77},
    {"aux_exp_relacional", "OR", 77},
    {"aux_exp_relacional", "RBRACKET", 77},
    {"aux_exp_relacional", "RPAREN", 77},
    {"aux_exp_relacional", "SEMICOLON", 77},

    {"op_rel", "GE", 81},
    {"op_rel", "GT", 79},
    {"op_rel", "LE", 80},
    {"op_rel", "LT", 78},

    {"expressao_aditiva", "CHAR_LIT", 82},
    {"expressao_aditiva", "FALSE", 82},
    {"expressao_aditiva", "FLOAT_LIT", 82},
    {"expressao_aditiva", "IDENT", 82},
    {"expressao_aditiva", "INT_LIT", 82},
    {"expressao_aditiva", "LPAREN", 82},
    {"expressao_aditiva", "MINUS", 82},
    {"expressao_aditiva", "NOT", 82},
    {"expressao_aditiva", "STRING_LIT", 82},
    {"expressao_aditiva", "TRUE", 82},

    {"aux_exp_aditiva", "AND", 85},
    {"aux_exp_aditiva", "ASSIGN", 85},
    {"aux_exp_aditiva", "COMMA", 85},
    {"aux_exp_aditiva", "EQ", 85},
    {"aux_exp_aditiva", "GE", 85},
    {"aux_exp_aditiva", "GT", 85},
    {"aux_exp_aditiva", "LE", 85},
    {"aux_exp_aditiva", "LT", 85},
    {"aux_exp_aditiva", "MINUS", 84},
    {"aux_exp_aditiva", "NE", 85},
    {"aux_exp_aditiva", "OR", 85},
    {"aux_exp_aditiva", "PLUS", 83},
    {"aux_exp_aditiva", "RBRACKET", 85},
    {"aux_exp_aditiva", "RPAREN", 85},
    {"aux_exp_aditiva", "SEMICOLON", 85},

    {"expressao_multiplicativa", "CHAR_LIT", 86},
    {"expressao_multiplicativa", "FALSE", 86},
    {"expressao_multiplicativa", "FLOAT_LIT", 86},
    {"expressao_multiplicativa", "IDENT", 86},
    {"expressao_multiplicativa", "INT_LIT", 86},
    {"expressao_multiplicativa", "LPAREN", 86},
    {"expressao_multiplicativa", "MINUS", 86},
    {"expressao_multiplicativa", "NOT", 86},
    {"expressao_multiplicativa", "STRING_LIT", 86},
    {"expressao_multiplicativa", "TRUE", 86},

    {"aux_exp_multiplicativa", "AND", 90},
    {"aux_exp_multiplicativa", "ASSIGN", 90},
    {"aux_exp_multiplicativa", "COMMA", 90},
    {"aux_exp_multiplicativa", "EQ", 90},
    {"aux_exp_multiplicativa", "GE", 90},
    {"aux_exp_multiplicativa", "GT", 90},
    {"aux_exp_multiplicativa", "LE", 90},
    {"aux_exp_multiplicativa", "LT", 90},
    {"aux_exp_multiplicativa", "MINUS", 90},
    {"aux_exp_multiplicativa", "NE", 90},
    {"aux_exp_multiplicativa", "OR", 90},
    {"aux_exp_multiplicativa", "PERCENT", 89},
    {"aux_exp_multiplicativa", "PLUS", 90},
    {"aux_exp_multiplicativa", "RBRACKET", 90},
    {"aux_exp_multiplicativa", "RPAREN", 90},
    {"aux_exp_multiplicativa", "SEMICOLON", 90},
    {"aux_exp_multiplicativa", "SLASH", 88},
    {"aux_exp_multiplicativa", "STAR", 87},

    {"expressao_unaria", "CHAR_LIT", 93},
    {"expressao_unaria", "FALSE", 93},
    {"expressao_unaria", "FLOAT_LIT", 93},
    {"expressao_unaria", "IDENT", 93},
    {"expressao_unaria", "INT_LIT", 93},
    {"expressao_unaria", "LPAREN", 93},
    {"expressao_unaria", "MINUS", 91},
    {"expressao_unaria", "NOT", 92},
    {"expressao_unaria", "STRING_LIT", 93},
    {"expressao_unaria", "TRUE", 93},

    {"expressao_posfixa", "CHAR_LIT", 94},
    {"expressao_posfixa", "FALSE", 94},
    {"expressao_posfixa", "FLOAT_LIT", 94},
    {"expressao_posfixa", "IDENT", 94},
    {"expressao_posfixa", "INT_LIT", 94},
    {"expressao_posfixa", "LPAREN", 94},
    {"expressao_posfixa", "STRING_LIT", 94},
    {"expressao_posfixa", "TRUE", 94},

    {"aux_exp_posfixa", "AND", 99},
    {"aux_exp_posfixa", "ASSIGN", 99},
    {"aux_exp_posfixa", "COMMA", 99},
    {"aux_exp_posfixa", "EQ", 99},
    {"aux_exp_posfixa", "GE", 99},
    {"aux_exp_posfixa", "GT", 99},
    {"aux_exp_posfixa", "LBRACKET", 95},
    {"aux_exp_posfixa", "LE", 99},
    {"aux_exp_posfixa", "LPAREN", 96},
    {"aux_exp_posfixa", "LT", 99},
    {"aux_exp_posfixa", "MINUS", 99},
    {"aux_exp_posfixa", "NE", 99},
    {"aux_exp_posfixa", "OR", 99},
    {"aux_exp_posfixa", "PERCENT", 99},
    {"aux_exp_posfixa", "PLUS", 99},
    {"aux_exp_posfixa", "RBRACKET", 99},
    {"aux_exp_posfixa", "RPAREN", 99},
    {"aux_exp_posfixa", "SEMICOLON", 99},
    {"aux_exp_posfixa", "SLASH", 99},
    {"aux_exp_posfixa", "STAR", 99},

    {"resto_chamada", "CHAR_LIT", 98},
    {"resto_chamada", "FALSE", 98},
    {"resto_chamada", "FLOAT_LIT", 98},
    {"resto_chamada", "IDENT", 98},
    {"resto_chamada", "INT_LIT", 98},
    {"resto_chamada", "LPAREN", 98},
    {"resto_chamada", "MINUS", 98},
    {"resto_chamada", "NOT", 98},
    {"resto_chamada", "RPAREN", 97},
    {"resto_chamada", "STRING_LIT", 98},
    {"resto_chamada", "TRUE", 98},

    {"argumentos", "CHAR_LIT", 100},
    {"argumentos", "FALSE", 100},
    {"argumentos", "FLOAT_LIT", 100},
    {"argumentos", "IDENT", 100},
    {"argumentos", "INT_LIT", 100},
    {"argumentos", "LPAREN", 100},
    {"argumentos", "MINUS", 100},
    {"argumentos", "NOT", 100},
    {"argumentos", "STRING_LIT", 100},
    {"argumentos", "TRUE", 100},

    {"resto_argumentos", "COMMA", 101},
    {"resto_argumentos", "RPAREN", 102},

    {"primario", "CHAR_LIT", 108},
    {"primario", "FALSE", 107},
    {"primario", "FLOAT_LIT", 105},
    {"primario", "IDENT", 103},
    {"primario", "INT_LIT", 104},
    {"primario", "LPAREN", 110},
    {"primario", "STRING_LIT", 109},
    {"primario", "TRUE", 106},
};

#endif
